name: OPA Policy Check

on:
  push:
    branches:
      - main

jobs:
  policy-check:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.3.0

      - name: Install Conftest
        uses: instrumenta/conftest-action@master

      - name: Run OPA Policy Check
        run: |
          conftest test config.json --policy policy/